---
#
# Playbook to install the ELK stack + Beats on MacOS
#
- name: Insall Elastic Stack components on MacOS
  hosts: localhost

  vars:
    version: "{{ version }}"
    repo_base_url: https://artifacts.elastic.co/downloads
    base_install_dir: /Users/sbrown/workspace/elastic-install

  roles:
    - { role: base_install, product: elasticsearch, product_family: elk,   target_os: }
    - { role: base_install, product: logstash,      product_family: elk,   target_os: }
    - { role: base_install, product: kibana,        product_family: elk,   target_os: darwin-x86_64 }
    - { role: base_install, product: apm-server,    product_family: elk,   target_os: darwin-x86_64 }
    - { role: base_install, product: metricbeat,    product_family: beats, target_os: darwin-x86_64 }
    - { role: base_install, product: filebeat,      product_family: beats, target_os: darwin-x86_64 }
#   - { role: base_install, product: packetbeat,    product_family: beats, target_os: darwin-x86_64 }
#  - { role: base_install, product: auditbeat,     product_family: beats, target_os: darwin-x86_64 }
